---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: spdkcsi-controller
spec:
  serviceName: spdkcsi-controller
  replicas: 1
  selector:
    matchLabels:
      app: spdkcsi-controller
  template:
    metadata:
      labels:
        app: spdkcsi-controller
    spec:
      serviceAccount: spdkcsi-controller-sa
      hostNetwork: true
      containers:
      - name: spdk-host
        image: c3y1huang/research:1-spdk
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: [ "bash", "-c", "/root/spdk/app/spdk_tgt/spdk_tgt & echo wait 5s... && sleep 5s && /root/spdk/scripts/rpc.py bdev_malloc_create -b Malloc0 1024 4096 && /root/spdk/scripts/rpc.py bdev_lvol_create_lvstore Malloc0 lvs0 && /root/spdk/scripts/rpc_http_proxy.py 127.0.0.1 9009 spdkcsiuser spdkcsipass" ]
        # command: [ "sleep", "infinity" ]
        ports:
        - containerPort: 9009
          name: http
        securityContext:
          privileged: true
        resources:
          limits:
            hugepages-2Mi: 2Gi
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: hugepage
          mountPath: /dev/hugepages
          readOnly: false
        - name: dshm
          mountPath: /dev/shm
          # readOnly: true
      - name: spdkcsi-registrar
        securityContext:
          privileged: true
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi.sock"
        - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.spdk.io/csi.sock"
        volumeMounts:
        - name: node-socket-dir
          mountPath: /csi
        - name: node-registration-dir
          mountPath: /registration
      - name: spdkcsi-node
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        image: c3y1huang/research:1-spdkcsi
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi.sock"
        - "--nodeid=$(NODE_ID)"
        - "--node"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c",
                        "/usr/sbin/iscsid || echo failed to start iscsid"]
        volumeMounts:
        - name: node-socket-dir
          mountPath: /csi
        - name: node-plugin-dir
          mountPath: /var/lib/kubelet/plugins
          mountPropagation: "Bidirectional"
        - name: node-pod-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        - name: node-host-dev
          mountPath: /dev
        - name: node-host-sys
          mountPath: /sys
      - name: spdkcsi-provisioner
        image: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--timeout=30s"
        - "--retry-interval-start=500ms"
        - "--leader-election=false"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: spdkcsi-attacher
        image: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--leader-election=false"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: spdkcsi-controller
        image: c3y1huang/research:1-spdkcsi
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi-provisioner.sock"
        - "--nodeid=$(NODE_ID)"
        - "--controller"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: spdkcsi-config
          mountPath: /etc/spdkcsi-config/
          readOnly: true
        - name: spdkcsi-secret
          mountPath: /etc/spdkcsi-secret/
          readOnly: true
      volumes:
      - name: socket-dir
        emptyDir:
          medium: "Memory"
      - name: spdkcsi-config
        configMap:
          name: spdkcsi-cm
      - name: spdkcsi-secret
        secret:
          secretName: spdkcsi-secret
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: node-socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/csi.spdk.io
          type: DirectoryOrCreate
      - name: node-registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: node-plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
      - name: node-pod-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
      - name: node-host-dev
        hostPath:
          path: /dev
      - name: node-host-sys
        hostPath:
          path: /sys
